export const BANK_NAMES = [
  "Aadhar Housing Finance", "Adani Housing Finance Pvt Ltd", "Ambit Finvest Pvt Ltd/Volition Credit & Holdings Pvt Ltd",
  "Anand Rathi", "ARKA Fincap Ltd", "Art Housing Finance India Limited", "AU Small Finance Bank",
  "Avanse Financial Services Ltd", "Axis Bank", "Axis Bank - ASHA", "Axis Bank - SBB Product",
  "Axis Bank (Connector)", "Axis Finance", "Bajaj Finance Ltd (Secured Product)", "Bajaj Finserv",
  "Bajaj Housing Finance Ltd", "Bandhan Bank Ltd", "Bank of Baroda", "Bank of India", "Bank of Maharashtra",
  "Canara Bank", "Capital India Finance Limited", "Capri Global Capital Limited", "Capri Global Housing Finance Limited",
  "Catholic Syrian Bank", "Cent Bank Home Finance Ltd", "Chola Mandalam Bank", "Clix Capital",
  "Credit Saison India", "CSL Finance", "DCB", "Deutsche Bank", "DMI Housing Finance Pvt Ltd",
  "Easy Home Finance Ltd", "Edelweiss (Nido)", "Equitas Finance", "Fasttrack Housing Finance Pvt Ltd",
  "Fedbank/Fedfina Financial Services Ltd", "Federal Bank", "Finnable", "Flexi Loans", "FT Cash",
  "Fullerton", "Fullerton India Home Finance (Grihashakti)", "GIC", "Godrej Housing Finance",
  "Growth Source Financial Technologies (Protium Finance Ltd)", "HDB Financial Services", "HDFC Bank",
  "HDFC Bank (Emerging)", "HDFC Credila", "Hero Fincorp", "Hero Housing Finance", "Hinduja Housing Finance Limited",
  "Home First Finance Company", "Homeshree Housing Finance Ltd", "HSBC", "ICICI Bank", "ICICI Bank - Digital",
  "ICICI Bank (Connector Code)", "ICICI Bank (DST) - Ghaziabad Only", "ICICI Bank (DST) - Pune Only",
  "ICICI Home Finance", "IDBI Bank", "IDFC First Bank", "IIFL", "IIFL-DST", "Incred", "IndiaBulls",
  "IndiaBulls (DSA)", "Indian Bank", "INDIFI", "Indostar", "IndusInd Bank", "Jana Small Finance Bank Ltd",
  "JM Financials Products Ltd", "Karur Vysya Bank", "Kotak Bank", "Kotak Prime", "L&T Finance",
  "L&T Finance (Connector)", "Lending Kart", "LIC Housing Finance Ltd", "M Capital (Ditya Finance Pvt Ltd)",
  "Mahindra Financial Services Ltd", "Mahindra Rural Home Finance Ltd", "MAS Financial Services Ltd",
  "MAS Rural Housing", "Moneywide (My Loancare Ventures Pvt Ltd)", "Motilal Oswal Home Finance Ltd (MOHFL)",
  "Muthoot Finance Ltd", "Muthoot Fincorp Ltd", "Muthoot HomeFin (INDIA) Ltd", "Muthoot Housing Finance Ltd",
  "Neo Growth", "Nivara Home Finance Ltd", "Niyogin Fintech Ltd", "Northern Arc Capital", "Piramal Housing Finance",
  "Piramal Housing Finance (DST)", "PNB Home Finance Ltd (PNBHFL)", "PNB Home Finance Ltd (PNBHFL) - DST",
  "Poonawalla Finance", "Profectus Capital", "Rattanindia Finance Pvt Ltd", "RBL Bank", "REPCO Home Finance",
  "Satin Housing Finance", "SBM Bank (State Bank of Mauritius)", "Shinhan Bank", "Shriram Finance Limited",
  "Shriram Housing Finance Ltd", "Shubh Loan", "Shubham Finance", "SMC Finance/Moneywise Financial Service Pvt Ltd",
  "SME Corner (Digikredit)", "SSA Finserv Private Limited", "Standard Chartered Bank (SCB)", "State Bank of India (SBI)",
  "State Bank of India (SBI) - Lucknow", "State Bank of India Capital (SBI Caps) - DST", "Sundaram Home Finance Ltd",
  "Suryoday Small Finance Bank Ltd", "Svatantra Micro Housing Finance", "Tata Housing Finance Ltd (DSA)",
  "Tata Housing Finance Ltd (DST)", "Tezzract Fintech Pvt Ltd", "UGRO Capital", "Ujjivan Small Finance Bank",
  "UMEED Housing Finance Co. Ltd", "Unity Small Finance Bank/Centrum Direct Ltd", "UPF Ltd",
  "Upwards Fintech Services Pvt Ltd", "Utkarsh Bank", "Vastu Housing Finance Corporation Ltd",
  "Whizdm Innovations Pvt Ltd (Moneyview)", "Yes Bank (DSA)", "Yes Bank (DST)", "Zip Loan",
  "Abhi Loan (KNAB Finance Advisors Pvt Ltd)", "Bhanix Finance & Investment Limited (Cashe)",
  "SRG Housing Finance Limited", "Indian Overseas Bank", "Aditya Birla Capital Ltd", "Kotak Agri",
  "Aditya Birla Housing Finance", "Punjab National Bank", "Krazybee Services Private Limited",
  "Aavas Financiers Limited", "Mangal Credit & Fincorp Ltd", "Central Bank of India",
  "KIFS Housing Finance Limited", "Agrim Housing Finance Pvt Ltd", "Ratnaafin Capital Pvt Ltd",
  "Kogta Financial (India) Ltd", "Tata Capital Financial Services Ltd", "Saraswat Bank", "Punjab & Sindh Bank",
  "L&T Consulting", "Aeon Credit Service India Pvt Ltd", "Kotak (Commercial) RBG verticle",
  "Axis Bank (Bharat Banking)", "Axis Bank Digital", "Jio Finance", "Saraswat Bank (CCBG)",
  "Varthana Finance", "Open Financial Technologies Pvt Ltd", "HDFC Consulting",
  "Tata Capital Financial Services Ltd (Digital)", "Car Dekho (Ruppy) finance", "Roha Housing Finance",
  "Sammaan Capital (Square Yards Consulting)", "Kotak Wholesale Business Banking (SME)",
  "(HomeVille Group) Creditworld Pvt Ltd", "Centrum Housing Finance Ltd", "Auxilo Finserv Pvt Ltd",
  "Rupeek (GL)", "Navi Fintech Pvt Ltd", "Hinduja Leyland Finance Limited", "PNB Cards & Services",
  "Union Bank of India (Mumbai)", "Bluebear Technology Pvt Ltd (Propelld)", "South Indian Bank Ltd",
  "Manappuram Finance Ltd", "United Capital (United Commerce)", "Grihum Housing Finance Limited",
  "J & K Bank (Delhi)", "Union Bank of India (Delhi)", "Finsol Code", "Home Credit India Finance Pvt Ltd",
  "FI (Epifi Technologies)", "Veritas Finance Limited", "Fusion Finance Ltd (Fittr)"
].sort();
